name: Generate Snake Game from Contributions

on:
  # Schedule to run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # Allows manual triggering of the workflow
  workflow_dispatch:
  
  # Run on every push to the master branch
  push:
    branches:
      - master
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Generate a snake game from a GitHub user's contributions graph and output a SVG animation
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: erenyurtcu
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Push the generated SVG files to the output branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
